# configuration file for TravisCI


# Notes:
#  - you can skip a build by adding [ci skip] to the commit message
#

# see http://about.travis-ci.org/docs/user/languages/java/
language: java

# test for these JDK versions and environments
jdk:
   - oraclejdk8
#   - oraclejdk7
#   - openjdk7

# only build these branches (RegEx is also valid, eg. /^deploy.*$/):
branches:
  only:
    - master

# container-based build:
sudo: false

#before_install:

#before_script:

# Run Integration tests
script: "mvn clean install sonar:sonar"

after_success:
  - mvn clean test jacoco:report coveralls:report

#after_failure:

#before_deploy:

deploy:
  - mvn tomcat7:redeploy

#after_deploy:

#after_script: